<a href="https://colab.research.google.com/github/sonalisanjeevprabu18/Neural-Network-and-Deep-Learning/blob/main/Tensorflow_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
A = np.array([[11, 24, 36],
              [4, 5, 6]])
B = np.array([[10, 20, 30],
              [40, 50, 60]])
C = A + B
print(C)


[[21 44 66]
 [44 55 66]]


In [3]:
import tensorflow as tf
A = tf.constant([[12,2,3],[45,5,6]])
B=tf.constant([[10,20,30],[40,50,60]])
C=A+B
print(C)

tf.Tensor(
[[22 22 33]
 [85 55 66]], shape=(2, 3), dtype=int32)
